import { roomAssetSets, roomCoverImages, type GalleryAsset } from "@/lib/media";

type LocalizedText = { de: string; en: string };

export interface Room {
  id: string;
  slug: string;
  name: LocalizedText;
  price: number;
  bookingPriceCnyPerNight: number;
  bookingPriceCnyTotal: number;
  bookingStayNights: number;
  bookingType: LocalizedText;
  maxGuests: number;
  beds: LocalizedText;
  sizeSqm: number;
  sizeSqft: number;
  description: LocalizedText;
  longDescription: LocalizedText;
  image: string;
  gallery: GalleryAsset[];
  amenities: string[];
  features: { de: string[]; en: string[] };
}

export const rooms: Room[] = [
  {
    id: "101",
    slug: "zimmer-101",
    name: { de: "Zimmer 101", en: "Room 101" },
    price: 140,
    bookingPriceCnyPerNight: 1049,
    bookingPriceCnyTotal: 3146,
    bookingStayNights: 3,
    bookingType: { de: "Doppelzimmer", en: "Double Room" },
    maxGuests: 2,
    beds: { de: "2 Einzelbetten", en: "2 twin beds" },
    sizeSqm: 25,
    sizeSqft: 269,
    description: {
      de: "Helles Doppelzimmer mit modernem Bad und Platz zum Arbeiten.",
      en: "Bright double room with a modern bathroom and space to work.",
    },
    longDescription: {
      de: "Zimmer 101 bietet ein ruhiges, gepflegtes Ambiente mit viel Tageslicht, warmem Holzboden und einem klaren modernen Look. Ideal fuer Paare oder Ring-Besucher, die ein entspanntes Doppelzimmer mit eigenem Bad suchen.",
      en: "Room 101 offers a calm, well-kept setting with plenty of daylight, warm wood flooring, and a clean modern look. It is ideal for couples or Ring visitors who want a relaxed double room with a private bathroom.",
    },
    image: roomCoverImages["101"],
    gallery: roomAssetSets["101"],
    amenities: ["wifi", "parking", "clean"],
    features: {
      de: [
        "Doppelbett",
        "Maximal 2 Erwachsene",
        "25 m²",
        "2 Einzelbetten",
        "Eigenes Badezimmer",
        "Kostenfreies WLAN",
        "Flachbild-TV",
        "Schreibtisch",
        "Kuehlschrank",
        "Tee-/Kaffeezubereiter",
        "Heizung",
        "Haartrockner",
        "Handtuecher und Bettwaesche",
      ],
      en: [
        "Double bed",
        "Max 2 adults",
        "25 m² / 269 ft²",
        "2 twin beds",
        "Private bathroom",
        "Free WiFi",
        "Flat-screen TV",
        "Desk",
        "Refrigerator",
        "Tea/coffee maker",
        "Heating",
        "Hairdryer",
        "Towels and bed linen",
      ],
    },
  },
  {
    id: "102",
    slug: "zimmer-102",
    name: { de: "Zimmer 102", en: "Room 102" },
    price: 140,
    bookingPriceCnyPerNight: 1049,
    bookingPriceCnyTotal: 3146,
    bookingStayNights: 3,
    bookingType: { de: "Doppelzimmer", en: "Double Room" },
    maxGuests: 2,
    beds: { de: "2 Einzelbetten", en: "2 twin beds" },
    sizeSqm: 25,
    sizeSqft: 269,
    description: {
      de: "Gemutliches Doppelzimmer mit kompakter Aufteilung und modernem Komfort.",
      en: "Cozy double room with a compact layout and modern comfort.",
    },
    longDescription: {
      de: "Zimmer 102 ist ein angenehmes Doppelzimmer mit klarer Ausstattung, warmen Farben und einem modernen Bad. Eine gute Wahl fuer kurze Wochenenden am Nuerburgring oder entspannte Tage in Adenau.",
      en: "Room 102 is a comfortable double room with clean lines, warm tones, and a modern bathroom. It is a strong choice for short Nuerburgring weekends or relaxed days in Adenau.",
    },
    image: roomCoverImages["102"],
    gallery: roomAssetSets["102"],
    amenities: ["wifi", "parking", "clean"],
    features: {
      de: [
        "Doppelbett",
        "Maximal 2 Erwachsene",
        "25 m²",
        "2 Einzelbetten",
        "Modernes Badezimmer",
        "Kostenfreies WLAN",
        "Flachbild-TV",
        "Sitz- und Arbeitsbereich",
        "Kuehlschrank",
        "Tee-/Kaffeezubereiter",
        "Heizung",
        "Haartrockner",
        "Handtuecher und Bettwaesche",
      ],
      en: [
        "Double bed",
        "Max 2 adults",
        "25 m² / 269 ft²",
        "2 twin beds",
        "Modern bathroom",
        "Free WiFi",
        "Flat-screen TV",
        "Seating and work area",
        "Refrigerator",
        "Tea/coffee maker",
        "Heating",
        "Hairdryer",
        "Towels and bed linen",
      ],
    },
  },
  {
    id: "103",
    slug: "zimmer-103",
    name: { de: "Dreibettzimmer 103", en: "Triple Room 103" },
    price: 210,
    bookingPriceCnyPerNight: 1573,
    bookingPriceCnyTotal: 4719,
    bookingStayNights: 3,
    bookingType: { de: "Dreibettzimmer", en: "Triple Room" },
    maxGuests: 3,
    beds: { de: "3 Einzelbetten", en: "3 twin beds" },
    sizeSqm: 30,
    sizeSqft: 323,
    description: {
      de: "Grosszuegiges Dreibettzimmer mit mehreren Schlafplaetzen fuer kleine Gruppen.",
      en: "Generous triple room with multiple sleeping spaces for small groups.",
    },
    longDescription: {
      de: "Dreibettzimmer 103 bietet mehr Flexibilitaet fuer Gaeste, die zusammen reisen. Der helle Raum verbindet drei Schlafmoeglichkeiten mit derselben modernen, gepflegten Ausstattung wie die anderen Zimmer im Haus.",
      en: "Triple Room 103 gives extra flexibility to guests traveling together. The bright space combines three sleeping options with the same modern, well-kept finish found throughout the house.",
    },
    image: roomCoverImages["103"],
    gallery: roomAssetSets["103"],
    amenities: ["wifi", "parking", "access", "clean"],
    features: {
      de: [
        "Mehrere Schlafplaetze",
        "Maximal 3 Erwachsene",
        "30 m²",
        "3 Einzelbetten",
        "Eigenes Badezimmer",
        "Kostenfreies WLAN",
        "Flachbild-TV",
        "Tisch und Sitzbereich",
        "Kuehlschrank",
        "Tee-/Kaffeezubereiter",
        "Heizung",
        "Haartrockner",
        "Handtuecher und Bettwaesche",
      ],
      en: [
        "Multiple sleeping spaces",
        "Max 3 adults",
        "30 m² / 323 ft²",
        "3 twin beds",
        "Private bathroom",
        "Free WiFi",
        "Flat-screen TV",
        "Table and seating area",
        "Refrigerator",
        "Tea/coffee maker",
        "Heating",
        "Hairdryer",
        "Towels and bed linen",
      ],
    },
  },
  {
    id: "201",
    slug: "zimmer-201",
    name: { de: "Komfortzimmer 201", en: "Comfort Room 201" },
    price: 140,
    bookingPriceCnyPerNight: 1049,
    bookingPriceCnyTotal: 3146,
    bookingStayNights: 3,
    bookingType: { de: "Doppelzimmer", en: "Double Room" },
    maxGuests: 2,
    beds: { de: "2 Einzelbetten", en: "2 twin beds" },
    sizeSqm: 25,
    sizeSqft: 269,
    description: {
      de: "Ruhiges Komfortzimmer unter dem Dach mit viel Licht und wohnlicher Atmosphaere.",
      en: "Quiet comfort room under the roof with plenty of light and a homely feel.",
    },
    longDescription: {
      de: "Zimmer 201 verbindet den ruhigen Charakter des oberen Stockwerks mit einem hellen Schlafbereich und einem grossen modernen Bad. Es passt gut zu Gaesten, die etwas mehr Rueckzug und eine entspannte Zimmeratmosphaere suchen.",
      en: "Room 201 combines the calm of the upper floor with a bright sleeping area and a spacious modern bathroom. It suits guests who want a little more privacy and a relaxed room atmosphere.",
    },
    image: roomCoverImages["201"],
    gallery: roomAssetSets["201"],
    amenities: ["wifi", "parking", "clean"],
    features: {
      de: [
        "Doppelbett",
        "Maximal 2 Erwachsene",
        "25 m²",
        "2 Einzelbetten",
        "Grosses Badezimmer",
        "Kostenfreies WLAN",
        "Flachbild-TV",
        "Schreibtisch",
        "Kuehlschrank",
        "Tee-/Kaffeezubereiter",
        "Heizung",
        "Haartrockner",
        "Handtuecher und Bettwaesche",
      ],
      en: [
        "Double bed",
        "Max 2 adults",
        "25 m² / 269 ft²",
        "2 twin beds",
        "Large bathroom",
        "Free WiFi",
        "Flat-screen TV",
        "Desk",
        "Refrigerator",
        "Tea/coffee maker",
        "Heating",
        "Hairdryer",
        "Towels and bed linen",
      ],
    },
  },
  {
    id: "202",
    slug: "zimmer-202",
    name: { de: "Komfortzimmer 202", en: "Comfort Room 202" },
    price: 240,
    bookingPriceCnyPerNight: 1798,
    bookingPriceCnyTotal: 5393,
    bookingStayNights: 3,
    bookingType: { de: "Familienzimmer mit Balkon", en: "Family Room with Balcony" },
    maxGuests: 4,
    beds: { de: "4 Einzelbetten", en: "4 twin beds" },
    sizeSqm: 50,
    sizeSqft: 538,
    description: {
      de: "Grosses, sonniges Doppelzimmer mit offenem Raumgefuehl und modernem Setup.",
      en: "Large, sunlit double room with an open feel and a modern setup.",
    },
    longDescription: {
      de: "Zimmer 202 wirkt besonders offen und freundlich. Viel Tageslicht, klare Materialien und ein grosszuegiger Grundriss machen es zu einer starken Wahl fuer alle, die etwas mehr Raum und Leichtigkeit im Aufenthalt suchen.",
      en: "Room 202 feels especially open and welcoming. Plenty of daylight, clean materials, and a generous layout make it a strong choice for guests who want a little more space and ease during their stay.",
    },
    image: roomCoverImages["202"],
    gallery: roomAssetSets["202"],
    amenities: ["wifi", "parking", "access", "clean"],
    features: {
      de: [
        "Doppelbett",
        "Maximal 4 Erwachsene",
        "50 m²",
        "4 Einzelbetten",
        "Balkon und Bergblick",
        "Eigenes Badezimmer",
        "Kostenfreies WLAN",
        "Flachbild-TV",
        "Sitz- und Arbeitsbereich",
        "Kuehlschrank",
        "Tee-/Kaffeezubereiter",
        "Heizung",
        "Haartrockner",
        "Handtuecher und Bettwaesche",
      ],
      en: [
        "Double bed",
        "Max 4 adults",
        "50 m² / 538 ft²",
        "4 twin beds",
        "Balcony and mountain view",
        "Private bathroom",
        "Free WiFi",
        "Flat-screen TV",
        "Seating and work area",
        "Refrigerator",
        "Tea/coffee maker",
        "Heating",
        "Hairdryer",
        "Towels and bed linen",
      ],
    },
  },
  {
    id: "203",
    slug: "zimmer-203",
    name: { de: "Komfortzimmer 203", en: "Comfort Room 203" },
    price: 140,
    bookingPriceCnyPerNight: 1049,
    bookingPriceCnyTotal: 3146,
    bookingStayNights: 3,
    bookingType: { de: "Economy Doppelzimmer", en: "Economy Double Room" },
    maxGuests: 2,
    beds: { de: "2 Einzelbetten", en: "2 twin beds" },
    sizeSqm: 25,
    sizeSqft: 269,
    description: {
      de: "Helles Doppelzimmer im oberen Stockwerk mit modernem Bad und ruhigem Arbeitsbereich.",
      en: "Bright upper-floor double room with a modern bathroom and a quiet work area.",
    },
    longDescription: {
      de: "Zimmer 203 ergaenzt die oberen Komfortzimmer mit einem freundlichen Schlafbereich, eigenem Bad und klarer Ausstattung. Es eignet sich sehr gut fuer Paare, Alleinreisende und Gaeste, die nach einem Tag am Nuerburgring einen ruhigen Rueckzugsort suchen.",
      en: "Room 203 completes the upper-floor comfort rooms with a welcoming sleeping area, private bathroom, and clean modern amenities. It works well for couples, solo travelers, and guests looking for a quiet retreat after a day at the Nuerburgring.",
    },
    image: roomCoverImages["203"],
    gallery: roomAssetSets["203"],
    amenities: ["wifi", "parking", "clean"],
    features: {
      de: [
        "Doppelbett",
        "Maximal 2 Erwachsene",
        "25 m²",
        "2 Einzelbetten",
        "Eigenes Badezimmer",
        "Kostenfreies WLAN",
        "Flachbild-TV",
        "Sitz- und Arbeitsbereich",
        "Heizung",
        "Handtuecher und Bettwaesche",
      ],
      en: [
        "Double bed",
        "Max 2 adults",
        "25 m² / 269 ft²",
        "2 twin beds",
        "Private bathroom",
        "Free WiFi",
        "Flat-screen TV",
        "Seating and work area",
        "Heating",
        "Towels and bed linen",
      ],
    },
  },
];
